#!/bin/sh
#PBS -l walltime=00:05:00
#PBS -l select=1:ncpus=4:mem=60gb
## #PBS -J 1-6
#PBS -m bea
## #PBS -M aeg116@ic.ac.uk
#PBS -N le-cc-g0998

## #PBS -q pqaero

module load intel-suite
module load mpi
#module load valgrind/3.11.0

CASE="VATT"
## OUTDIR=${WORK}/${CASE}-${PBS_ARRAY_INDEX}
OUTDIR=${WORK}/${CASE}

VALGR=""
#VALGR="valgrind --tool=memcheck --log-file=${HOME}/cases/EulEul/${CASE}/memcheck%p.txt"

cp ${PBS_O_WORKDIR}/incompact3d ${TMPDIR}/incompact3d

echo ${TMPDIR} > ${PBS_O_WORKDIR}/where_am_i

## pbsexec -grace 20 mpiexec ${VALGR} ./incompact3d > OUTPUT.log-${PBS_ARRAY_INDEX}

## Copy the input files at the location of the executable in the WORK directory
mpiexec ${TMPDIR}/incompact3d ${PBS_O_WORKDIR}/input.i3d ${TMPDIR}/input.i3d > OUTPUT.log

mkdir -p ${OUTDIR}
cp *.log ${OUTDIR}/
cp *restart* ${OUTDIR}/
cp ux* ${OUTDIR}/
cp uy* ${OUTDIR}/
cp uz* ${OUTDIR}/
cp pp* ${OUTDIR}/
cp vort* ${OUTDIR}/
cp epsi* ${OUTDIR}/

#cp ux* ${OUTDIR}/
#cp uy* ${OUTDIR}/
#cp rho* ${OUTDIR}/
#cp pp* ${OUTDIR}/
#cp vort* ${OUTDIR}/
#cp uz* ${OUTDIR}/
#cp *.dat ${OUTDIR}/
