#
#        FILE: Makefile for Test-Convergence
# DESCRIPTION: Governs running Test-Convergence test cases for Xcompact3D.
#      AUTHOR: Paul Bartholomew <paul.bartholomew08@imperial.ac.uk>
#

NP = 1
TEST = ALL

